service: BGCWebScraper
frameworkVersion: "3"

plugins:
  - serverless-esbuild

custom:
  tableName: "ProductsTable-${sls:stage}"
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    PRODUCTS_TABLE: ${self:custom.tableName}

functions:
  getProducts:
    handler: src/controllers/productsController.getProducts
    events:
      - httpApi:
          path: /products
          method: GET

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
